### ISSUE TITLE
When Bag slot change, feed button seems like not choose any diet

### ISSUE THREAD

**Issue by amberGit** [Beast-Masters-addons/feed-o-matic#12] opened 2019-12-07 16:53 UTC
Imagine that my hunter player's bag has two bundle of diet, one called A, another called B, and A has 1 left, B remains 5.  first I click feed button, it works, A has been fed. so now only has B, and then I click  
feed button but cannot feed. I open the debug mode, the log told me B is choosed but feed button not work. so  what's the problem?

**Comment by datagutten** [comment] 2023-12-21 15:19
I was not able to reproduce this when I tested it now. I might have fixed it earlier without closing the issue. Please re-open the issue if you still experience the problem.

**Closed as completed by datagutten** 2023-12-21 15:19 UTC
